---
title: ''
geometry:
  - left=1.5cm
  - right=1.5cm
  - top=2.5cm
  - bottom=2.5cm

output: pdf_document
params:
  table: NA
  assay_date: NA
  plate_number: NA
header-includes:
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \usepackage{booktabs}
  - \pagestyle{fancy}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{xcolor}
  
---

```{r load_packages, message=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)

table_output <- params$table
```

```{r prepare_filename, echo=FALSE}
plate_number <- str_replace_all(params$plate_number, "_", "-")
header_name <- paste(params$assay_date, plate_number)
```

\fancyhead[CO,C]{`r header_name`}
\cfoot{\thepage\ of \pageref{LastPage}}

```{r print_table, message=FALSE, echo=FALSE}

options(knitr.kable.NA = "", knitr.table.format = "latex")

names(table_output) <- sub("_", " ", names(table_output))


table_output %>%
  mutate(`IgG Resultat` = cell_spec(`IgG Resultat`, align = "r", background = if_else(`IgG Resultat` == "pos", "#bfbfbf", "#ffffff")),
         `IgA Resultat` = cell_spec(`IgA Resultat`, align = "r", background = if_else(`IgA Resultat` == "pos", "#bfbfbf", "#ffffff")),
         `IgM Resultat` = cell_spec(`IgM Resultat`, align = "r", background = if_else(`IgM Resultat` == "pos", "#bfbfbf", "#ffffff"))) %>%
  
  mutate(`IgG NP` = cell_spec(round(`IgG NP`, 1), align = "r",
                              background = case_when(
                                `IgG NP` > 1 ~ "#06aed5",
                                `IgG NP` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgG S2` = cell_spec(round(`IgG S2`, 1), align = "r",
                              background = case_when(
                                `IgG S2` > 1 ~ "#06aed5",
                                `IgG S2` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgG S1` = cell_spec(round(`IgG S1`, 1), align = "r",
                              background = case_when(
                                `IgG S1` > 1 ~ "#06aed5",
                                `IgG S1` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff"))) %>%
  
    mutate(`IgA NP` = cell_spec(round(`IgA NP`, 1), align = "r",
                              background = case_when(
                                `IgA NP` > 1 ~ "#06aed5",
                                `IgA NP` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgA S2` = cell_spec(round(`IgA S2`, 1), align = "r",
                              background = case_when(
                                `IgA S2` > 1 ~ "#06aed5",
                                `IgA S2` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgA S1` = cell_spec(round(`IgA S1`, 1), align = "r",
                              background = case_when(
                                `IgA S1` > 1 ~ "#06aed5",
                                `IgA S1` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff"))) %>%
  
      mutate(`IgM NP` = cell_spec(round(`IgM NP`, 1), align = "r",
                              background = case_when(
                                `IgM NP` > 1 ~ "#06aed5",
                                `IgM NP` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgM S2` = cell_spec(round(`IgM S2`, 1), align = "r",
                              background = case_when(
                                `IgM S2` > 1 ~ "#06aed5",
                                `IgM S2` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff")),
         `IgM S1` = cell_spec(round(`IgM S1`, 1), align = "r",
                              background = case_when(
                                `IgM S1` > 1 ~ "#06aed5",
                                `IgM S1` >= 0.9 ~ "#ffe74c",
                                TRUE ~ "#ffffff"))) %>%

  kable(escape = F, booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("scale_down"))
  

```

