---
title: "VirMet Report"
output: pdf_document
params:
  orgs_file: ""
  reads_file: ""
  sample_name: ""
  user_name: ""
  rows_selected: ""
  checkbox_phages: ""
  blacklist_file: ""
  checkbox_blacklist: ""
---

```{r load-packages, include=FALSE}
library(tidyr)
library(cowplot)
library(dplyr)
library(ggplot2)
library(readr)
library(knitr)
library(stringr)
library(forcats)
```

```{r read-data, include=FALSE}
blacklist <-
  read_csv(params$blacklist_file)

orgs_data <-
  read_delim(params$orgs_file, "\t") %>%
  mutate(covered_percent = 100 * covered_region / seq_len,
         covered_max = 100 * reads * 151 / seq_len,
         covered_max = if_else(covered_max > 100, 100, covered_max),
         covered_score = round(100 * covered_percent / covered_max, 1),
         covered_percent = round(covered_percent, 1))

# if in shiny app selected, remove entries containing "phage"
if (isTRUE(params$checkbox_phages)) {
  orgs_data <-
    orgs_data %>%
    filter(grepl("phage", species, ignore.case = TRUE) == FALSE) %>%
    filter(grepl("phage", ssciname, ignore.case = TRUE) == FALSE)
}

# if in shiny app selected, remove entries from blacklist provided
if (isTRUE(params$checkbox_blacklist)) {
  orgs_data <-
    orgs_data %>%
    anti_join(blacklist, by = "stitle")
}

reads_data <-
  read_delim(params$reads_file, "\t")
```

## Run Information
```{r run-information, echo=FALSE, comment=NA, tidy=TRUE}
run_name <-
  reads_data$run[1]

filtered_reads_dna <-
  reads_data %>%
  filter(category == "passing_filter",
         sample %in% params$sample_name,
         str_detect(sample, "DNA")) %>%
  select(reads) %>%
  as.integer()

filtered_reads_rna <-
  reads_data %>%
  filter(category == "passing_filter",
         sample %in% params$sample_name,
         str_detect(sample, "RNA")) %>%
  select(reads) %>%
  as.integer()

molis_nr <-
  unique(str_extract(params$sample_name, "\\d{10,}-*[A-z]*(?=-)"))



t_info <-
  data.frame() %>%
  rbind(data.frame(key = "Run name", value = run_name)) %>%
  rbind(data.frame(key = "Sample name", value = params$sample_name)) %>%
  rbind(data.frame(key = "Quality-filtered reads (DNA/RNA)", value = paste0(round(filtered_reads_dna/1000000, 3), "/", round(filtered_reads_rna/1000000, 3), " M"))) %>%
  rbind(data.frame(key = "Report date", value = factor(Sys.Date())))

# User name doesn't work if shiny app was used on the shiny server
t_info <- rbind(t_info, data.frame(key = "User name", value = params$user_name))
row.names(t_info) <- NULL
colnames(t_info) <- NULL

kable(t_info)
```

---
subtitle: `r molis_nr`
---

## Domain Level Taxonomy Profile
```{r read-category, echo=FALSE, fig.width=6, fig.height=2.5}
domain <-
  reads_data %>%
  filter(sample %in% params$sample_name) %>%
  filter(!(category == "raw_reads" | category == "passing_filter" | category == "reads_to_blast")) %>%
  mutate(domain = case_when(
    category %in% c("matching_bact1", "matching_bact2", "matching_bact3") ~ "bacterial",
    category %in% c("viral_reads") ~ "viral",
    category %in% c("matching_humanGRCh38") ~ "human",
    category %in% c("undetermined_reads") ~ "undetermined",
    category %in% c("matching_bt_ref") ~ "bovine",
    category %in% c("matching_fungi1") ~ "fungal",
    TRUE ~ "none")) %>%
  mutate(workflow = case_when(
    str_detect(sample, "DNA") ~ "DNA",
    str_detect(sample, "RNA") ~ "RNA",
    TRUE ~ "none")) %>%
  filter(!(domain == "none"),
         !(workflow == "none"))

domain_order <- c("human", "bacterial", "fungal", "bovine", "viral", "undetermined")

t_domain <-
  domain %>%
  select(domain, reads) %>%
  group_by(domain) %>%
  mutate(reads = sum(reads)) %>%
  sample_n(1) %>%
  ungroup() %>%
  mutate(domain = fct_relevel(domain, domain_order)) %>%
  arrange(domain) %>%
  mutate(percent = round(reads/sum(reads)*100, 3)) %>%
  mutate(abundance = strrep("+", 1 + round(percent/max(percent)*19)))

kable(t_domain)

domain_plot <-
  domain %>%
  select(domain, workflow, reads) %>%
  group_by(domain, workflow) %>%
  mutate(reads = sum(reads)) %>%
  sample_n(1) %>%
  ggplot(aes(x = fct_relevel(domain, rev(domain_order)), y = reads)) +
  geom_col(aes(fill = workflow), colour = "black", position = "dodge") +
  scale_y_log10() +
  scale_fill_manual(values = c("white", "grey")) +
  coord_flip() +
  labs(x = NULL)
```

## Detected[^1] Virus Species

```{r list-relevant, results='asis', echo=FALSE}
t_species <-
  orgs_data %>%
  filter(sample %in% params$sample_name) %>%
  mutate(workflow = case_when(
    str_detect(sample, "DNA") ~ "DNA workflow",
    str_detect(sample, "RNA") ~ "RNA workflow",
    TRUE ~ "none")) %>%
  select(species, reads, workflow) %>%
  group_by(species, workflow) %>%
  summarise(reads_sum = sum(reads)) %>%
  spread(key = workflow, value = reads_sum, fill = 0) %>%
  ungroup() %>%
  mutate(total = as.integer(rowSums(.[,-1], na.rm = TRUE))) %>%
  mutate(percent = round(total/sum(total)*100, 3)) %>%
  arrange(desc(total)) %>%
  select(-percent)

t_species_selected <-
  t_species[params$rows_selected, ]

#if (nrows(t_species_selected)) >= 1 {kable(t_species_selected)}

if (nrow(t_species_selected) == 0) {
    cat("No relevant virus species detected.")
} else {
    kable(t_species_selected)
}

```

[^1]: excluding phages and endogenous retroviruses

\newpage

## Rejected Virus Species
```{r list-rejected, echo = FALSE}
t_species_unselected <-
  setdiff(t_species, t_species_selected)

kable(t_species_unselected)
```

```{r additional-statements, echo=FALSE, comment=NA}
# Print statements in report if phages or blacklisted viruses were removed
phages_removed_text <- ""
if (isTRUE(params$checkbox_phages)) {
  phages_removed_text <- "Virus species containing 'phage' were excluded."
}

blacklisted_text <- ""
if (isTRUE(params$checkbox_blacklist)) {
  blacklisted_text <- "Blacklisted references[^2] were excluded."
}

```

`r phages_removed_text`

`r blacklisted_text`

[^2]: false annotated references